### PR TITLE
Add delete if not in source capability.

### PR DESCRIPTION
**Pull request by LiquoriChris**

### CODE REVIEW

**Comment by LiquoriChris** [comment]
@NowinskiK I didn't update the module version in the `psd1` as I am not sure how the version gets updated

**Comment by NowinskiK** [comment]
That's great, thanks! Can you add new line in `changelog` (you can assume new version as `0.22`) describing what you've added?

**Comment by LiquoriChris** [comment]
Added to changelog. Please let me know if anything else needs to be done.

**Comment by NowinskiK** [comment]
close #27

**Pull request merged**
